// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH0gWnlX5Bydd3LCI2Ojau0ELo0P2R1hQ',
    appId: '1:7818637938:web:5610588bb7af40977f48eb',
    messagingSenderId: '7818637938',
    projectId: 'signin-example-f124c',
    authDomain: 'signin-example-f124c.firebaseapp.com',
    storageBucket: 'signin-example-f124c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsJKQm4tgb6kAOElzpsKMoMkW47adnx0U',
    appId: '1:7818637938:android:247f4ca63141f6cd7f48eb',
    messagingSenderId: '7818637938',
    projectId: 'signin-example-f124c',
    storageBucket: 'signin-example-f124c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqtKlUt-3bvpv1wagnafWpSntbqJkTJ6o',
    appId: '1:7818637938:ios:ab669322e0b72bb57f48eb',
    messagingSenderId: '7818637938',
    projectId: 'signin-example-f124c',
    storageBucket: 'signin-example-f124c.appspot.com',
    iosClientId: '7818637938-69nkoboan2vb0dhifiph5j0cofbqrkis.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaselogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqtKlUt-3bvpv1wagnafWpSntbqJkTJ6o',
    appId: '1:7818637938:ios:563565942c8c455d7f48eb',
    messagingSenderId: '7818637938',
    projectId: 'signin-example-f124c',
    storageBucket: 'signin-example-f124c.appspot.com',
    iosClientId: '7818637938-4e6j41vfm3f85m7kdlphkspnq3rubjdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaselogin.RunnerTests',
  );
}
